

const quotes = [
    {quote: '"The only way to do great work is to love what you do."', person: '"Steve Jobs"', designation: 'Co-founder of Apple'},
    {quote: '"Believe you can and you\'re halfway there."', person: '"Theodore Roosevelt"', designation: '26th US President'},
    {quote: '"Success usually comes to those who are too busy to be looking for it."', person: '"Henry David Thoreau"', designation: 'Essayist'},
    {quote: '"The best revenge is massive success."', person: '"Frank Sinatra"', designation: 'Singer and Actor'},
    {quote: '"In the middle of every difficulty lies opportunity."', person: '"Albert Einstein"', designation: 'Physicist'},
    {quote: '"You miss 100% of the shots you don\'t take."', person: '"Wayne Gretzky"', designation: 'Former Hockey Player'},
    {quote: '"A person who never made a mistake never tried anything new."', person: '"Albert Einstein"', designation: 'Physicist'},
    {quote: '"The only person you should try to be better than is the person you were yesterday."', person: 'Unknown', designation: 'Unknown'},
    {quote: '"I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination."', person: '"Jimmy Dean"', designation: 'Actor and Singer'},
    {quote: '"It does not matter how slowly you go as long as you do not stop."', person: '"Confucius"', designation: 'Philosopher'},
    {quote: '"The two most important days in your life are the day you are born and the day you find out why."', person: '"Mark Twain"', designation: 'Writer'},
    {quote: '"Don\'t watch the clock; do what it does. Keep going."', person: '"Sam Levenson"', designation: 'Humorist and Author'},
    {quote: '"Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle."', person: 'Unknown', designation: 'Unknown'},
    {quote: '"You are never too old to set another goal or to dream a new dream."', person: '"C.S. Lewis"', designation: 'Writer'},
    {quote: '"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."', person: '"Albert Schweitzer"', designation: 'Theologian and Philosopher'},
    {quote: '"It always seems impossible until it is done."', person: '"Nelson Mandela"', designation: 'Former President'},
    {quote: '"You don\'t have to be great to start, but you have to start to be great."', person: 'Unknown', designation: 'Unknown'},
    {quote: '"If you want to achieve greatness stop asking for permission."', person: '"Anonymous"', designation: 'N/A'},
    {quote: '"Life is 10% what happens to us and 90% how we react to it."', person: '"Charles R. Swindoll"', designation: 'Writer and Speaker'},
    {quote: '"The only limit to our realization of tomorrow will be our doubts of today."', person: '"Franklin D. Roosevelt"', designation: '32nd US President'},
    {quote: '"Do not wait for the perfect moment, take the moment and make it perfect."', person: '"Zoey Sayward"', designation: 'Author'},
    {quote: '"The greatest glory in living lies not in never falling, but in rising every time we fall."', person: '"Nelson Mandela"', designation: 'Former President'},
    {quote: '"It\'s not the load that breaks you down, it\'s the way you carry it."', person: '"Lou Holtz"', designation: 'Former Football Coach'},
    {quote: '"Success is not final, failure is not fatal: It is the courage to continue that counts."', person: '"Winston Churchill"', designation: 'Former UK Prime Minister'},
    {quote: '"The future belongs to those who believe in the beauty of their dreams."', person: '"Eleanor Roosevelt"', designation: 'Former US First Lady'},
    {quote: '"The only person you should try to be better than is the person you were yesterday."', person: 'Unknown', designation: 'Unknown'},
    {quote: '"Believe you can and you\'re halfway there."', person: '"Theodore Roosevelt"', designation: '26th US President'},
    {quote: '"Keep your face always toward the sunshine—and shadows will fall behind you."', person: '"Walt Whitman"', designation: 'Poet'},
    {quote: '"The biggest adventure you can take is to live the life of your dreams."', person: '"Oprah Winfrey"', designation: 'Media Mogul'},
    {quote: '"Life is either a daring adventure or nothing at all."', person: '"Helen Keller"', designation: 'Author and Activist'},
    {quote: '"Success is not in what you have, but who you are."', person: '"Bo Bennett"', designation: 'Author and Speaker'},
    {quote: '"The future starts today, not tomorrow."', person: '"Pope John Paul II"', designation: 'Former Pope'},
    {quote: '"Your time is limited, don\'t waste it living someone else\'s life."', person: '"Steve Jobs"', designation: 'Co-founder of Apple'},
    {quote: '"The best way to predict the future is to create it."', person: '"Peter Drucker"', designation: 'Management Consultant'},
    {quote: '"Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears."', person: '"Chantal Sutherland"', designation: 'Jockey'},
    {quote: '"The only place where success comes before work is in the dictionary."', person: '"Vidal Sassoon"', designation: 'Hairdresser and Entrepreneur'},
    {quote: '"Don\'t let yesterday take up too much of today."', person: '"Will Rogers"', designation: 'Actor and Humorist'},
    {quote: '"Success is walking from failure to failure with no loss of enthusiasm."', person: '"Winston Churchill"', designation: 'Former UK Prime Minister'},
    {quote: '"The harder I work, the luckier I get."', person: '"Gary Player"', designation: 'Professional Golfer'},
    {quote: '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward."', person: '"Rocky Balboa"', designation: 'Fictional Character'},
    {quote: '"Opportunities don\'t happen. You create them."', person: '"Chris Grosser"', designation: 'Photographer and Speaker'},
    {quote: '"The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks."', person: '"Mark Zuckerberg"', designation: 'Co-founder of Facebook'},
    {quote: '"The true measure of success is how many times you can bounce back from failure."', person: '"Stephen Richards"', designation: 'Author and Speaker'},
    {quote: '"The only thing we have to fear is fear itself."', person: '"Franklin D. Roosevelt"', designation: '32nd US President'},
    {quote: '"Success is not just about making money. It\'s about making a difference."', person: '"Unknown"', designation: 'Unknown'},
    {quote: '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart."', person: '"Roy T. Bennett"', designation: 'Author'},
    {quote: '"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do."', person: '"Steve Jobs"', designation: 'Co-founder of Apple'},
    {quote: '"Believe you can and you\'re halfway there."', person: '"Theodore Roosevelt"', designation: '26th US President'},
    {quote: '"Keep your face always toward the sunshine—and shadows will fall behind you."', person: '"Walt Whitman"', designation: 'Poet'},
    {quote: '"The biggest adventure you can take is to live the life of your dreams."', person: '"Oprah Winfrey"', designation: 'Media Mogul'},
    {quote: '"Life is either a daring adventure or nothing at all."', person: '"Helen Keller"', designation: 'Author and Activist'},
    {quote: '"Success is not in what you have, but who you are."', person: '"Bo Bennett"', designation: 'Author and Speaker'},
    {quote: '"The future starts today, not tomorrow."', person: '"Pope John Paul II"', designation: 'Former Pope'},
    {quote: '"Your time is limited, don\'t waste it living someone else\'s life."', person: '"Steve Jobs"', designation: 'Co-founder of Apple'},
    {quote: '"The best way to predict the future is to create it."', person: '"Peter Drucker"', designation: 'Management Consultant'},
    {quote: '"Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears."', person: '"Chantal Sutherland"', designation: 'Jockey'},
    {quote: '"The only place where success comes before work is in the dictionary."', person: '"Vidal Sassoon"', designation: 'Hairdresser and Entrepreneur'},
    {quote: '"The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it."', person: '"Jordan Belfort"', designation: 'Author and Motivational Speaker'},
    {quote: '"Don\'t let yesterday take up too much of today."', person: '"Will Rogers"', designation: 'Actor and Humorist'},
    {quote: '"Success is walking from failure to failure with no loss of enthusiasm."', person: '"Winston Churchill"', designation: 'Former UK Prime Minister'},
    {quote: '"The harder I work, the luckier I get."', person: '"Gary Player"', designation: 'Professional Golfer'},
    {quote: '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward."', person: '"Rocky Balboa"', designation: 'Fictional Character'},
    {quote: '"Opportunities don\'t happen. You create them."', person: '"Chris Grosser"', designation: 'Photographer and Speaker'},
    {quote: '"The true measure of success is how many times you can bounce back from failure."', person: '"Stephen Richards"', designation: 'Author and Speaker'},
    {quote: '"The only thing we have to fear is fear itself."', person: '"Franklin D. Roosevelt"', designation: '32nd US President'},
    {quote: '"Success is not just about making money. It\'s about making a difference."', person: '"Unknown"', designation: 'Unknown'},
    {quote: '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart."', person: '"Roy T. Bennett"', designation: 'Author'},
    {quote: '"Dream big and dare to fail."', person: '"Norman Vaughan"', designation: 'Adventurer'},
    {quote: '"The only limit to our realization of tomorrow will be our doubts of today."', person: '"Franklin D. Roosevelt"', designation: '32nd US President'},
    {quote: '"A successful man is one who can lay a firm foundation with the bricks others have thrown at him."', person: '"David Brinkley"', designation: 'Journalist'},
    {quote: '"The greatest glory in living lies not in never falling, but in rising every time we fall."', person: '"Nelson Mandela"', designation: 'Former President'},
    {quote: '"It\'s not the load that breaks you down, it\'s the way you carry it."', person: '"Lou Holtz"', designation: 'Former Football Coach'},
    {quote: '"Success is not final, failure is not fatal: It is the courage to continue that counts."', person: '"Winston Churchill"', designation: 'Former UK Prime Minister'},
    {quote: '"The future belongs to those who believe in the beauty of their dreams."', person: '"Eleanor Roosevelt"', designation: 'Former US First Lady'},
    {quote: '"The only person you should try to be better than is the person you were yesterday."', person: 'Unknown', designation: 'Unknown'},
    {quote: '"Believe you can and you\'re halfway there."', person: '"Theodore Roosevelt"', designation: '26th US President'},
    {quote: '"Keep your face always toward the sunshine—and shadows will fall behind you."', person: '"Walt Whitman"', designation: 'Poet'},
    {quote: '"The biggest adventure you can take is to live the life of your dreams."', person: '"Oprah Winfrey"', designation: 'Media Mogul'},
    {quote: '"Life is either a daring adventure or nothing at all."', person: '"Helen Keller"', designation: 'Author and Activist'},
    {quote: '"Success is not in what you have, but who you are."', person: '"Bo Bennett"', designation: 'Author and Speaker'},
    {quote: '"The future starts today, not tomorrow."', person: '"Pope John Paul II"', designation: 'Former Pope'},
    {quote: '"Your time is limited, don\'t waste it living someone else\'s life."', person: '"Steve Jobs"', designation: 'Co-founder of Apple'},
    {quote: '"The best way to predict the future is to create it."', person: '"Peter Drucker"', designation: 'Management Consultant'},
    {quote: '"Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears."', person: '"Chantal Sutherland"', designation: 'Jockey'},
    {quote: '"The only place where success comes before work is in the dictionary."', person: '"Vidal Sassoon"', designation: 'Hairdresser and Entrepreneur'},
    {quote: '"Don\'t let yesterday take up too much of today."', person: '"Will Rogers"', designation: 'Actor and Humorist'},
    {quote: '"Success is walking from failure to failure with no loss of enthusiasm."', person: '"Winston Churchill"', designation: 'Former UK Prime Minister'},
    {quote: '"The harder I work, the luckier I get."', person: '"Gary Player"', designation: 'Professional Golfer'},
    {quote: '"It\'s not about how hard you hit. It\'s about how hard you can get hit and keep moving forward."', person: '"Rocky Balboa"', designation: 'Fictional Character'},
    {quote: '"Opportunities don\'t happen. You create them."', person: '"Chris Grosser"', designation: 'Photographer and Speaker'},
    {quote: '"The true measure of success is how many times you can bounce back from failure."', person: '"Stephen Richards"', designation: 'Author and Speaker'},
    {quote: '"The only thing we have to fear is fear itself."', person: '"Franklin D. Roosevelt"', designation: '32nd US President'},
    {quote: '"Success is not just about making money. It\'s about making a difference."', person: '"Unknown"', designation: 'Unknown'},
    {quote: '"Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart."', person: '"Roy T. Bennett"', designation: 'Author'},
    { quote: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", person: "Helen Keller", designation: "Author" },
    {quote: 'The best and most beautiful things in the world ca… even touched - they must be felt with the heart.', person: 'Helen Keller', designation: 'Author'},
    {quote: "The only way to do great work is to love what you …haven't found it yet, keep looking. Don't settle.", person: 'Steve Jobs', designation: 'Entrepreneur'}, 
    {quote: 'The only way to fail is to give up.', person: 'Albert Einstein', designation: 'Scientist'},
    {quote: 'The difference between ordinary and extraordinary is that little extra.', person: 'Jimmy Johnson', designation: 'Football coach'},
    {quote: 'The future belongs to those who believe in the beauty of their dreams.', person: 'Eleanor Roosevelt', designation: 'First Lady'},
    {quote: 'The best way to do something is to begin.', person: 'Plato', designation: 'Philosopher'},
    {quote: 'The only person who is in control of your happiness is you.', person: 'Unknown', designation: ''}, 
    {quote: 'The best way to find yourself is to lose yourself in the service of others.', person: 'Mahatma Gandhi', designation: 'Religious leader'},
    {quote: 'The journey of a thousand miles begins with a single step.', person: 'Lao Tzu', designation: 'Philosopher'},
    {quote: 'The mind is everything. What you think you become.', person: 'Buddha', designation: 'Religious leader'},
    {quote: 'The best way to predict the future is to create it.', person: 'Peter Drucker', designation: 'Management consultant'},
    {quote: 'The only thing that is constant is change.', person: 'Heraclitus', designation: 'Philosopher'},
    {quote: 'The only person you are destined to become is the person you decide to be.', person: 'Ralph Waldo Emerson', designation: 'Author'}, 
    {quote: 'The best and most beautiful things in the world cannot be bought, they must be earned.', person: 'Maya Angelou', designation: 'Poet'},


];


function a(){

    let random = Math.floor(Math.random() * quotes.length)
    console.log(random)

    document.querySelector('.quote').innerText = quotes[random].quote;
    document.querySelector('.name').innerText = quotes[random].person;
    document.querySelector('.designation').innerText = quotes[random].designation;

}