# print(binaryS([1,2,3,4,5,6] , 4))

# def BS(L,k) :
#     begin = 0 
#     end = len(L) - 1 

#     while end - begin > 1 :

#         mid = (end + begin) // 2

#         if L[mid] == k :
#             return 1 
#         if L[mid] > k :
#             end = mid - 1 
#         if L[mid] < k :
#             begin = mid + 1 

#     if L[begin] == k or L[end] == k :
#         return 1 
#     else :
#         return 0 
    
# print(BS([1,2,3,4,5,6,7,8,9,10] , 2 ))
